### ISSUE TITLE
Can there be any issues caused by selfdestruct?

### ISSUE THREAD

**Issue by PaulRBerg** [wETH-v2/wETH-v2#36]
When a contract is [self-destructed](https://ethereum.stackexchange.com/questions/315/why-are-selfdestructs-used-in-contract-programming), the remaining ETH is sent to a designated address.

Afaik, this is a way to send ETH to a contract that doesn't trigger that contract's `receive` function (formerly the fallback function).

Could this cause WETH10 to malfunction?

**Comment by dmihal** [comment]
With a cursory glance of the code, I can't think of any issues this would cause, since the contract's ETH balance is never explicitly checked.

Of course, the totalSupply wouldn't match the sum of all WETH balances (it would fail my [token auditor](https://twitter.com/dmihal/status/1294048740853112833)), but I don't think this would cause any actual problems in practice.

**Comment by albertocuestacanada** [comment]
Wouldn't the address for the self-destructed contract just get a positive WETH balance?

That would mean that contracts created with CREATE2 could sent their ETH to be stored as WETH, and then another contract redeployed at the same address could recover the ETH.

I don't see any issues, to me it seems just as a regular use of the WETH contract.

**Comment by dmihal** [comment]
@albertocuestacanada When ETH is transferred using selfdestruct, the fallback function isn't called, so WETH isn't minted

**Comment by albertocuestacanada** [comment]
Ah, that's unfortunate. Still, it doesn't break anything.

**Comment by PaulRBerg** [comment]
Cool, just wanted to check.
